[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api"
  to = "/api/"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/swagger-ui/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"